### PR TITLE
fix_bug_rgb_input

### PR DESCRIPTION
**Pull request by lm-jira**
Change the code to deal with RGB input instead of BGR input.

### CODE REVIEW

**Comment by hadusam** [comment]
ok to test

**Comment by ruimashita** [comment]
@lm-jira I think the bug doesn't be fixed by this PR.
We should change input of `run_inference()` to RGB.

**Comment by lm-jira** [comment]
@ruimashita Thank you for your comment
I changed the input image from BGR to RGB in run_inference in this pull request.
However, the result is not improved as I expected because it misclassifies my faces as background.
The accuracy is still good in airplanes and motorbikes classification.

**Comment by ruimashita** [comment]
@lm-jira Thanks, LGTM. I will verify to work.

**Comment by ruimashita** [comment]
I verified that the script work well with my face detection model,
Also when the camera capture blue image, the `img[:, :, 0]` values of after [this line](https://github.com/blue-oil/blueoil/pull/5/files#diff-9ca1efa1ec38e2e985c8ae39464b3182R66) are close `0`.

**Comment by lm-jira** [comment]
Thank you for the verification.

**Pull request merged**
