### PR TITLE
Refactor cpp code

### PR DESCRIPTION
**Pull request by lm-noshiro**
## What this patch does to fix the issue.

* removed redundant flush immediately after `endl`
* use `empty()` instead of `size() == 0`
* reduce recalculation

### CODE REVIEW

**Comment by iizukak** [comment]
@kchygoe @tfujiwar 
make build failed in CI.
Do you have any idea?
https://buildkite.com/blueoil/dlk-test/builds/2779#3aa45ba7-6ccd-4601-8e15-5fe8c35a203f

**Comment by kchygoe** [comment]
let me check the test env

**Comment by kchygoe** [comment]
@iizukak Resolved test. It works correctly now. sorry for the inconvenience.

**Comment by iizukak** [comment]
@kchygoe Thanks 🙇

**Pull request merged**
