### PR TITLE
Motion jpeg server for demo

### PR DESCRIPTION
**Pull request by ruimashita**
## Motivation and Context

Currently demo script `use_camera_demo.py` is hard to use because it need X server and to connect ssh, I created demo motion jpeg server script for usb camera to easy view demo on user's browser.
And I create `lmnet.visualize` module for handling output and input image to draw result image for each task. 

***This PR need to create document to use this demo but I didn't do yet. I will do it in anothre PR.***

## Description

* Implement the entry point script `motion_jpeg_server_from_camera.py` .
* Implement the module of visualization of result image for each task `lmnet/lmnet/visualize.py` , and unit test.
* Implement `VideoStream` wrapping `cv2.VideoCapture` on thread,  in `output_template/python/lmnet/utils/demo.py` 
* Refactoring `output_template/python/lmnet/utils/demo.py`.
* Compatible python v2 `lmnet/lmnet/post_processor.py`.

## How has this been tested?

I verified the demo script work on DE10-Nano for each tasks and then I was able to connect from my firefox browser.

`python2 python/motion_jpeg_server_from_camera.py -l ./models/lib/lib_fpga.so -c ./models/meta.yaml`

## Screenshots (if appropriate):

object detection
Screen Shot 2019-04-24 at 20 27 33

semantic segmentation
Screen Shot 2019-04-24 at 20 26 50

classification
Screen Shot 2019-04-24 at 20 24 37

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature / Optimization (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ruimashita** [comment]
@iizukak @lm-jira @nlpng Review plz 😄

**Comment by iizukak** [comment]
I'll try this PR today.

**Comment by nlpng** [comment]
Checked demo of segmentation for CamVid dataset, works properly.

Screen Shot 2019-04-25 at 11 47 09

**Comment by iizukak** [comment]
@ruimashita The following error was occured when run `motion_jpeg_server_from_camera.py`
```
# python2 python/motion_jpeg_server_from_camera.py -l ./models/lib/lib_fpga.so -c ./models/meta.yaml
python/motion_jpeg_server_from_camera.py:208: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  help="Port number of motion jpege server."
python/motion_jpeg_server_from_camera.py:228: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  main()
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /build/opencv-zRYBJW/opencv-2.4.9.1+dfsg/modules/imgproc/src/color.cpp, line 3648
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/home/iizuka/blueoil/saved/face_20190410151344/export/save.ckpt-161187/224x224/output/python/lmnet/utils/demo.py", line 124, in update
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
error: /build/opencv-zRYBJW/opencv-2.4.9.1+dfsg/modules/imgproc/src/color.cpp:3648: error: (-215) scn == 3 || scn == 4 in function cvtColor
```

**Comment by iizukak** [comment]
Sorry, my os missing the webcam.

**Comment by iizukak** [comment]
Will merge after test passed.

**Comment by ruimashita** [comment]
@iizukak @nlpng Thanks for test 😄😄😄

**Pull request merged**
