### PR TITLE
Fix pass_lookup()

### PR DESCRIPTION
**Pull request by yd8534976**
Current implementation of `pass_lookup() ` hard-coded the next operation following `lookup`. Since input names are different between each ops. (e.g. Conv: ['X', 'W', 'B'], SpaceToDepth: ['input']) It will fail to convert some cases. #346 
I fix it to deal with more cases. (Thank @nlpng for helping.)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature / Optimization (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by iizukak** [comment]
@antonionevado Can you check?

**Comment by yd8534976** [comment]
@antonionevado I updated the implementation. Please check it. 🙇

**Comment by antonionevado** [comment]
@yd8534976 Do we have any [dlk] test that uses a protobuf file with a Lookup layer?

**Comment by yd8534976** [comment]
@antonionevado Thanks! I test it with [a pb file](https://drive.google.com/open?id=1MNP_-J98ZQfqCwmoAx5USLpeGiv0SOpi). It works fine with this file.

**Comment by yd8534976** [comment]
@antonionevado The failed case in #346 .

**Pull request merged**
