### PR TITLE
Fix #343. Enable to load config file under lmnet dir

### LINKED ISSUE #343: lmnet train.py raise ModuleNotFoundError when config file is under lmnet directory
`lmnet/executor/train.py` raise ModuleNotFoundError when config file is under lmnet directory.

```  
$ docker run \
        --rm \
        -it \
        --runtime=nvidia \
        -e PYTHONPATH=/home/blueoil:/home/blueoil/lmnet:/home/blueoil/dlk/python/dlk \
        -e OUTPUT_DIR=/home/blueoil/saved \
        -e CUDA_VISIBLE_DEVICES=2 \
        -v /storage/dataset:/home/blueoil/dataset \
        -v $(pwd)/saved:/home/blueoil/saved \
        blueoil_$(id -un):4456f1c-dirty \
        python lmnet/executor/train.py -c lmnet/configs/example/classification.py
```

Raise error:
```
Traceback (most recent call last):
  File "lmnet/executor/train.py", line 416, in <module>
    main()
  File "/usr/local/pyenv/versions/python3.6/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/pyenv/versions/python3.6/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/pyenv/versions/python3.6/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/pyenv/versions/python3.6/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "lmnet/executor/train.py", line 412, in main
    run(network, dataset, config_file, experiment_id, recreate)
  File "lmnet/executor/train.py", line 361, in run
    config = config_util.load(config_file)
  File "/home/blueoil/lmnet/lmnet/utils/config.py", line 118, in load
    config = loader(config_file)
  File "/home/blueoil/lmnet/lmnet/utils/config.py", line 126, in _load_py
    config_module = module_loader.load_module(config_file)
  File "/home/blueoil/lmnet/lmnet/utils/module_loader.py", line 38, in load_module
    module = importlib.import_module(module_path)
  File "/usr/local/pyenv/versions/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lmnet.configs'
```

### PR DESCRIPTION
**Pull request by ruimashita**
Fix #343

## Description

To fix #343, Load lmnet config file using abs path.

## How has this been tested?

I verified this command don't raise error.
```
   docker run \
        --rm \
        -it \
        --runtime=nvidia \
        -e PYTHONPATH=/home/blueoil:/home/blueoil/lmnet:/home/blueoil/dlk/python/dlk \
        -e OUTPUT_DIR=/home/blueoil/saved \
        -e CUDA_VISIBLE_DEVICES=2 \
        -v /storage/dataset:/home/blueoil/dataset \
        -v $(pwd)/saved:/home/blueoil/saved \
        blueoil_$(id -un):4456f1c-dirty \
        python lmnet/executor/train.py -c lmnet/configs/example/classification.py
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature / Optimization (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ruimashita** [comment]
@Joeper214 
Thanks 👍  Need to run conmand on `/blueoil/` , not `/blueoil/lmne/`

**Comment by Joeper214** [comment]
> @Joeper214
> Thanks 👍 Need to run conmand on `/blueoil/` , not `/blueoil/lmne/`

Yeah, same situation on `~/blueoil$  ` directory

**Comment by ruimashita** [comment]
@Joeper214 
umm 🤔  Did you run `make` command ?

**Comment by Joeper214** [comment]
@ruimashita Yes I did.

**Comment by ruimashita** [comment]
@Joeper214 Thanks 🎉

**Comment by ruimashita** [comment]
run lmnet test

**Pull request merged**
