### PR TITLE
fix branch bug

### PR DESCRIPTION
**Pull request by lm-konda**
## Motivation and Context
Fix apply threshold logic bug
related to #99 

## Description
change branch condition same as
```
https://github.com/blue-oil/blueoil/blob/master/dlk/python/dlk/templates/src/func/impl/quantized_conv2d_dim2col.cpp
```
This code looks more correct.

## How has this been tested?
run on X86 / ARM / FPGA. All networks are correct.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature / Optimization (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by tkng** [comment]
Sorry, I still don't fully understand the code, but the original code looks correct for me. Could you explain a little bit more detail?

**Comment by lm-konda** [comment]
The original repository is probably updated after this PR.
Because I committed once and difference is these part only.

**Comment by lm-konda** [comment]
This is an evidence.
https://github.com/blue-oil/blueoil/blob/v0.2.1/dlk/python/dlk/templates/src/func/impl/apply_thresholds.cpp

**Comment by tkng** [comment]
Oops, sorry, I was checking the code after you fixed 🙇 

LGTM.

**Pull request merged**
