### PR TITLE
Add PerImageStandardization compatibility in (C++ inference) runtime

### PR DESCRIPTION
**Pull request by oatawa1**
## What this patch does to fix the issue.
The PerImageStandardization is already implemented but it is not in the mapping process.
This PR adds mapping process node to functions vector.

## Link to any relevant issues or pull requests.
https://github.com/blue-oil/blueoil/issues/1020#issuecomment-628419387

### CODE REVIEW

**Comment by iizukak** [comment]
@oatawa1 
How about to add unit test

**Comment by oatawa1** [comment]
@iizukak great idea. Let's me try.

**Comment by oatawa1** [comment]
@iizukak Thank you. Should I proceed with this PR and create a new PR for the unit test?

**Comment by primenumber** [comment]
RA :+1:

**Comment by oatawa1** [comment]
@primenumber Thank you.

**Pull request merged**
