### PR TITLE
Remove output_event.py

### PR DESCRIPTION
**Pull request by iizukak**
Solve #1218

### CODE REVIEW

**Comment by oatawa1** [comment]
@iizukak Could you resolve the CI failed?

How about removing the output_event unit test?
https://github.com/blue-oil/blueoil/blob/master/tests/unit/executor_tests/test_output_event.py

**Comment by iizukak** [comment]
@oatawa1 Thanks. Removed.

**Review by oatawa1 — APPROVED** [review]
LGTM. Thanks.

**Comment by iizukak** [comment]
@oatawa1 
Thanks.

**Pull request merged**
