### PR TITLE
[Experimental] Add parameter tuning feature to lmnet

### PR DESCRIPTION
**Pull request by nlpng**
## Motivation and Context

This WIP PR is trying to enhance productivity for lmnet training by integrating hyper-parameter search through supporting two existing frameworks such as the Ray. The current implementation is rather immature, and subject to change.

## Description

This PR added new supports for the [Ray](https://github.com/ray-project/ray) frameworks to the lmnet, also their dependencies.
We are going to separate the PR into smaller PRs, the main changes in here are under `lmnet/executor`.
newly added:
- `tune_ray.py`

Next [PR](https://github.com/blue-oil/blueoil/pull/215) will be in the `lmnet/configs` for new tunable config files.
Currently tested tunable configurations:
- `lmnet_v1_quantize_cifar10_tune.py`
- `segnet_quantize_camvid_tune.py`

## How has this been tested?

Soon adding the testing reports.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature / Optimization (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ruimashita** [comment]
There are so many duplicate lines with executor/train.py
It is the time to create a module for training like lmnet/train.py

**Comment by iizukak** [comment]
@nlpng 
Thanks you for sweet new feature!

I test with [camvid_tune.py](https://github.com/blue-oil/blueoil/pull/215/files#diff-17b15df9488839d228c511606e652a17) with this branch.

Turning and training start correctly but while running, under the error has occurred.

```
 - tunable_100_learning_rate=8.8131e-05,scheduler=<function piecewise_constant at 0x2b8c7dac5510>,scheduler_factor=1.0,scheduler_steps=(25000, 50000, 75000),lm_config=_home_iizuka_blueoil_lmnet_configs_core_segmentation_segnet_quantize_ca
mvid_tune.py,optimizer=<class 'tensorflow.python.training.adam.AdamOptimizer'>:       ERROR, 1 failures: /home/iizuka/ray_results/exp_tune/tunable_100_learning_rate=8.8131e-05,scheduler=<function piecewise_constant at 0x2b8c7dac5510>,sche
duler_factor=1.0,scheduler_step_2019-04-25_19-26-41xiayupfb/error_2019-04-25_19-28-15.txt
TERMINATED trials:
 - tunable_1_learning_rate=0.0010983,scheduler=<function piecewise_constant at 0x2b8c7dac5510>,scheduler_factor=1.0,scheduler_steps=(25000, 50000, 75000),lm_config=_home_iizuka_blueoil_lmnet_configs_core_segmentation_segnet_quantize_camvi
d_tune.py,optimizer=<class 'tensorflow.python.training.adam.AdamOptimizer'>:  TERMINATED, [2 CPUs, 1 GPUs], [pid=27976], 1837 s, 200 iter, 0.239 acc
 - tunable_2_learning_rate=0.0072559,scheduler=<function piecewise_constant at 0x2b8c7dac5510>,scheduler_factor=1.0,scheduler_steps=(25000, 50000, 75000),lm_config=_home_iizuka_blueoil_lmnet_configs_core_segmentation_segnet_quantize_camvi
d_tune.py,optimizer=<class 'tensorflow.python.training.adam.AdamOptimizer'>:  TERMINATED, [2 CPUs, 1 GPUs], [pid=27975], 1737 s, 200 iter, 0.387 acc

Traceback (most recent call last):
  File "executor/tune_ray.py", line 296, in <module>
    main()
  File "/home/iizuka/venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/iizuka/venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/iizuka/venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/iizuka/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "executor/tune_ray.py", line 292, in main
    run(config_file, tunable_id, local_dir)
  File "executor/tune_ray.py", line 267, in run
    trials = run_experiments(experiments={'exp_tune': tune_spec}, search_alg=algo, scheduler=scheduler)
  File "/home/iizuka/venv/lib/python3.6/site-packages/ray/tune/tune.py", line 189, in run_experiments
    raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [tunable_3_learning_rate=0.0094536,scheduler=<function piecewise_constant at 0x2b8c7dac5510>,scheduler_factor=1.0,scheduler_steps=(25000, 50000, 75000),lm_config=_home_iizuka_blueoil_l
mnet_configs_core_segmentation_segnet_quantize_camvid_tune.py,optimizer=<class 'tensorflow.python.training.adam.AdamOptimizer'>, tunable_4_learning_rate=0.0015272,scheduler=<function piecewise_constant at 0x2b8c7dac5510>,scheduler_factor=
1.0,scheduler_steps=(25000, 50000, 75000),lm_config=_home_iizuka_blueoil_lmnet_configs_core_segmentation_segnet_quantize_camvid_tune.py,optimizer=<class 'tensorflow.python.training.adam.AdamOptimizer'>, tunable_5_learning_rate=0.0073068,s
cheduler=<function piecewise_constant at 0x2b8c7dac5510>,scheduler_factor=1.0,scheduler_steps=(25000, 50000, 75000),lm_config=_home_iizuka_blueoil_lmnet_configs_core_segmentation_segnet_quantize_camvid_tune.py,optimizer=<class 'tensorflow
.python.training.adam.AdamOptimizer'>, tunable_6_learning_rate=0.0019631,scheduler=<function piecewise_constant at 0x2b8c7dac5510>,scheduler_factor=1.0,scheduler_steps=(25000, 50000, 75000),lm_config=_home_iizuka_blueoil_lmnet_configs_cor
e_segmentation_segnet_quantize_camvid_tune.py,optimizer=<class 'tensorflow.python.training.adam.AdamOptimizer'>, tunable_7_learning_rate=0.0093679,scheduler=<function piecewise_constant at 0x2b8c7dac5510>,scheduler_factor=1.0,scheduler_st
eps=(25000, 50000, 75000),lm_config=_home_iizuka_blueoil_lmnet_configs_core_segmentation_segnet_quantize_camvid_tune.py,optimizer=<class 'tensorflow.python.training.adam.AdamOptimizer'>, tunable_8_learning_rate=0.00043018,scheduler=<funct
ion piecewise_constant at 0x2b8c7dac5510>,scheduler_factor=1.0,scheduler_steps=(25000, 50000, 75000),lm_config=_home_iizuka_blueoil_lmnet_configs_core_segmentation_segnet_quantize_camvid_tune.py,optimizer=<class 'tensorflow.python.trainin
g.adam.AdamOptimizer'>, tunable_9_learning_rate=0.0078337,scheduler=<function piecewise_constant at 0x2b8c7dac5510>,scheduler_factor=1.0,scheduler_steps=(25000, 50000, 75000),lm_config=_home_iizuka_blueoil_lmnet_configs_core_segmentation_
segnet_quantize_camvid_tune.py,optimizer=<class 'tensorflow.python.training.adam.AdamOptimizer'>, tunable_10_learning_rate=0.00049669,scheduler=<function piecewise_constant at 0x2b8c7dac5510>,scheduler_factor=1.0,scheduler_steps=(25000, 5
0000, 75000),lm_config=_home_iizuka_blueoil_lmnet_configs_core_segmentation_segnet_quantize_camvid_tune.py,optimizer=<class 'tensorflow.python.training.adam.AdamOptimizer'>, tunable_11_learning_rate=0.0058122,scheduler=<function piecewise
_constant at 0x2b8c7dac5510>,scheduler_factor=1.0,scheduler_steps=(25000, 50000, 75000),lm_config=_home_iizuka_blueoil_lmnet_configs_core_segmentation_segnet_quantize_camvid_tune.py,optimizer=<class 'tensorflow.python.training.adam.AdamOp
timizer'>, tunable_12_learning_rate=0.0099653,scheduler=<function piecewise_constant at 0x2b8c7dac5510>,s
```

**Comment by iizukak** [comment]
I run both classification and semantic segmentation.
Looks good.

Semantic Segmentation + CamVid
スクリーンショット 2019-04-26 14 00 15

Classification + CIFAR10
スクリーンショット 2019-04-26 15 19 11

**Comment by iizukak** [comment]
run test

**Pull request merged**
