### PR TITLE
Update converter test to PY3 and drop py2 functions

### PR DESCRIPTION
**Pull request by kchygoe**
## What this patch does to fix the issue.
 - Update `test_code_generation` to use python3 expressly 
 - Drop PY2 functionalities from output_template
 
## Link to any relevant issues or pull requests.

### CODE REVIEW

**Comment by kchygoe** [comment]
@iizukak ping

**Comment by kchygoe** [comment]
> Thank you!! There are some remaining **future**. Do we need to remove them also?

Thank you for the check! Let me include them. (I thought I checked all...)

**Comment by kchygoe** [comment]
Fixed!

**Review by iizukak — APPROVED** [review]
OA

**Comment by iizukak** [comment]
@kchygoe Sorry, one file was conflicted.

**Comment by kchygoe** [comment]
got it!

**Comment by kchygoe** [comment]
rebased

**Pull request merged**
