### PR TITLE
Remove func_QTZ_binary_channel_wise_mean_scaling

### PR DESCRIPTION
**Pull request by primenumber**
## Motivation and Context

This function is not used anymore.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature / Optimization (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by primenumber** [comment]
related #569 .

**Comment by primenumber** [comment]
@tkng How about is this PR?

**Comment by tkng** [comment]
Let me clarify my understanding. `QTZ_binary_channel_wise_mean_scaling` is always optimized out by optimizer, hence we don't need this implementation.

I'm worried that removing this implementation won't make it harder to test, but I don't have concrete evidence that it shouldn't be removed.

**Comment by tkng** [comment]
Since restoring implementation is not difficult, now I'm thinking it's OK to merge.

**Pull request merged**
