### PR TITLE
Fix docstring and documentation typo.

### PR DESCRIPTION
**Pull request by oatawa1**

### CODE REVIEW

**Review by iizukak — APPROVED** [review]
OA

**Comment by oatawa1** [comment]
@iizukak Thank you.

**Review by tfujiwar — APPROVED** [review]
RA, LGTM
Thank you! I think it's enough to have a title `Fix docstring and documentation typo.` without any description.

**Comment by oatawa1** [comment]
@tfujiwar Thank you for your review and advice.

**Pull request merged**
