### PR TITLE
Show progressbar during training

### PR DESCRIPTION
**Pull request by tsawada**
Currently lmnet prints a line per a step during training, which makes it hard to
scroll back anything before the training begins.

### CODE REVIEW

**Comment by iizukak** [comment]
@tsawada Thanks.
@nlpng Can you check this PR?

**Comment by tsawada** [comment]
rebased to latest master

**Comment by Joeper214** [comment]
@tsawada Looks like the forked repo is gone.

**Comment by tsawada** [comment]
oops I accidentally deleted the original branch.
Please look at https://github.com/tsawada/blueoil/tree/progbar

**Comment by iizukak** [comment]
@Joeper214 Can you test this PR?

**Pull request merged**
