### PR TITLE
[WIP] make Quantized format ChHWBCl

### PR DESCRIPTION
**Pull request by primenumber**
Fix output types and memory layout of Quantize.

## Motivation and Context

In some network, dlk generate broken code...
This is because type/layout are wrong.

## Description

If hard quantize is enabled, fix output type and layout of QTZ_linear_mid_tread_half.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature / Optimization (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tkng** [comment]
I'm not sure when dlk generates broken code. Could you tell me an example situation?

**Comment by primenumber** [comment]
Main problem is layout of output tensor vary.
Types of input for one concat_on_depth may vary, that will cause compile error.
This PR unify layouts to ChHWBCl, but Supporting layout-mixed concat_on_depth ( #472 ) may be better than this solution...

**Comment by tkng** [comment]
Thanks, now I understand a bit deeply than before.

This PR looks changing output format of `func_QTZ_linear_mid_tread_half` to `ChHWBCl` (so that subsequent `concat_on_depth` works), so merging both of this PR and #472 looks fine. Is my understanding correct?

**Comment by primenumber** [comment]
This PR force upgrade dtype and layout of output of QTZ_linear_mid_tread_half, it cause compile error in some networks.
This issue is linked with #474 , but this PR is very ad-hoc...

**Comment by tkng** [comment]
> This issue is linked with #474 , but this PR is very ad-hoc...

Though this PR might be ad-hoc, if there's no drawback, I'd like to merge this PR.
@primenumber I'll merge this PR tomorrow, could you tell me if you want to withdraw this PR?

**Pull request closed without merging**
