### PR TITLE
Documentation for time measurement.

### PR DESCRIPTION
**Pull request by ed728**
Added documentation for time measurement.
## Motivation and Context

#319.

Also related to #330.

## Description

Added an extra page to the usage section of our documentation to describe how to measure inference speed.

## How has this been tested?

TBD.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature / Optimization (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ed728** [comment]
NOTE!!!
Not in a complete state yet.

TBD:
-Testing proof and screenshots for the record.
-Once #330 is done, add a section for measuring time for any binary using the `lib_*.so` files. This should also have a note about overflow and accumulation.
-Add output example from latest `HEAD`.

**Comment by iizukak** [comment]
@Joeper214 Can you check time measurement with @ed728 -san's document?

**Comment by Joeper214** [comment]
> @Joeper214 Can you check time measurement with @ed728 -san's document?

Sure. I'll do that.

**Comment by iizukak** [comment]
Please update with current master branch.

**Comment by iizukak** [comment]
スクリーンショット 2019-07-29 16 56 24

@ed728 
Thank you for update.
But still can not merge this PR...

**Pull request merged**
