### PR TITLE
Change executor/profile_model.py to delete training only operation from profile output

### PR DESCRIPTION
**Pull request by ruimashita**
* Fix to delete training only operation from profile markdown.
* Show image size and number of classes in profile markdown.
* Prompt output file path in the end.
* Change wording `Flops` to `FLOPs`.

## Motivation and Context

Change executor/profile_model.py to delete training only operation from profile output.
And more useful information to profile output.

## How has this been tested?

run this command
```
$ docker-compose -p lmnet run --rm cpu-tensorflow python3 executor/profile_model.py -c configs/core/object_detection/yolo_v2_quantize_pascalvoc_2007_2012.py
```
output this markdown.
# YoloV2Quantize

* Image size: {height: 416, width: 416}
* Number of class: 20

| Name | Param | Size (MB) | 32 bits Quant Size (MB) | FLOPs (m) |
| :-- | --: | --: | --: | --: |
| **total** | **50655389** | **193.23497** | **193.23497** | **29360.70209** |
| **block_1** | **928** | **0.00354** | **0.00354** | **299.04077** |
| &nbsp;&nbsp;block_1/bn | 64 | 0.00024 | 0.00024 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_1/bn/beta | 32 | 0.00012 | 0.00012 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_1/bn/gamma | 32 | 0.00012 | 0.00012 | - |
| &nbsp;&nbsp;block_1/conv | 864 | 0.0033 | 0.0033 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_1/conv/kernel | 864 | 0.0033 | 0.0033 | - |
| **block_2** | **18560** | **0.0708** | **0.0708** | **1594.8841** |
| &nbsp;&nbsp;block_2/bn | 128 | 0.00049 | 0.00049 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_2/bn/beta | 64 | 0.00024 | 0.00024 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_2/bn/gamma | 64 | 0.00024 | 0.00024 | - |
| &nbsp;&nbsp;block_2/conv | 18432 | 0.07031 | 0.07031 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_2/conv/kernel | 18432 | 0.07031 | 0.07031 | - |
| **block_3** | **73984** | **0.28223** | **0.28223** | **1594.8841** |
| &nbsp;&nbsp;block_3/bn | 256 | 0.00098 | 0.00098 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_3/bn/beta | 128 | 0.00049 | 0.00049 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_3/bn/gamma | 128 | 0.00049 | 0.00049 | - |
| &nbsp;&nbsp;block_3/conv | 73728 | 0.28125 | 0.28125 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_3/conv/kernel | 73728 | 0.28125 | 0.28125 | - |
| **block_4** | **8320** | **0.03174** | **0.03174** | **177.20934** |
| &nbsp;&nbsp;block_4/bn | 128 | 0.00049 | 0.00049 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_4/bn/beta | 64 | 0.00024 | 0.00024 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_4/bn/gamma | 64 | 0.00024 | 0.00024 | - |
| &nbsp;&nbsp;block_4/conv | 8192 | 0.03125 | 0.03125 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_4/conv/kernel | 8192 | 0.03125 | 0.03125 | - |
| **block_5** | **73984** | **0.28223** | **0.28223** | **1594.8841** |
| &nbsp;&nbsp;block_5/bn | 256 | 0.00098 | 0.00098 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_5/bn/beta | 128 | 0.00049 | 0.00049 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_5/bn/gamma | 128 | 0.00049 | 0.00049 | - |
| &nbsp;&nbsp;block_5/conv | 73728 | 0.28125 | 0.28125 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_5/conv/kernel | 73728 | 0.28125 | 0.28125 | - |
| **block_6** | **295424** | **1.12695** | **1.12695** | **1594.8841** |
| &nbsp;&nbsp;block_6/bn | 512 | 0.00195 | 0.00195 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_6/bn/beta | 256 | 0.00098 | 0.00098 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_6/bn/gamma | 256 | 0.00098 | 0.00098 | - |
| &nbsp;&nbsp;block_6/conv | 294912 | 1.125 | 1.125 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_6/conv/kernel | 294912 | 1.125 | 1.125 | - |
| **block_7** | **33024** | **0.12598** | **0.12598** | **177.20934** |
| &nbsp;&nbsp;block_7/bn | 256 | 0.00098 | 0.00098 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_7/bn/beta | 128 | 0.00049 | 0.00049 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_7/bn/gamma | 128 | 0.00049 | 0.00049 | - |
| &nbsp;&nbsp;block_7/conv | 32768 | 0.125 | 0.125 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_7/conv/kernel | 32768 | 0.125 | 0.125 | - |
| **block_8** | **295424** | **1.12695** | **1.12695** | **1594.8841** |
| &nbsp;&nbsp;block_8/bn | 512 | 0.00195 | 0.00195 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_8/bn/beta | 256 | 0.00098 | 0.00098 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_8/bn/gamma | 256 | 0.00098 | 0.00098 | - |
| &nbsp;&nbsp;block_8/conv | 294912 | 1.125 | 1.125 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_8/conv/kernel | 294912 | 1.125 | 1.125 | - |
| **block_9** | **1180672** | **4.50391** | **4.50391** | **1594.8841** |
| &nbsp;&nbsp;block_9/bn | 1024 | 0.00391 | 0.00391 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_9/bn/beta | 512 | 0.00195 | 0.00195 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_9/bn/gamma | 512 | 0.00195 | 0.00195 | - |
| &nbsp;&nbsp;block_9/conv | 1179648 | 4.5 | 4.5 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_9/conv/kernel | 1179648 | 4.5 | 4.5 | - |
| **block_10** | **131584** | **0.50195** | **0.50195** | **177.20934** |
| &nbsp;&nbsp;block_10/bn | 512 | 0.00195 | 0.00195 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_10/bn/beta | 256 | 0.00098 | 0.00098 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_10/bn/gamma | 256 | 0.00098 | 0.00098 | - |
| &nbsp;&nbsp;block_10/conv | 131072 | 0.5 | 0.5 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_10/conv/kernel | 131072 | 0.5 | 0.5 | - |
| **block_11** | **1180672** | **4.50391** | **4.50391** | **1594.8841** |
| &nbsp;&nbsp;block_11/bn | 1024 | 0.00391 | 0.00391 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_11/bn/beta | 512 | 0.00195 | 0.00195 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_11/bn/gamma | 512 | 0.00195 | 0.00195 | - |
| &nbsp;&nbsp;block_11/conv | 1179648 | 4.5 | 4.5 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_11/conv/kernel | 1179648 | 4.5 | 4.5 | - |
| **block_12** | **131584** | **0.50195** | **0.50195** | **177.20934** |
| &nbsp;&nbsp;block_12/bn | 512 | 0.00195 | 0.00195 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_12/bn/beta | 256 | 0.00098 | 0.00098 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_12/bn/gamma | 256 | 0.00098 | 0.00098 | - |
| &nbsp;&nbsp;block_12/conv | 131072 | 0.5 | 0.5 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_12/conv/kernel | 131072 | 0.5 | 0.5 | - |
| **block_13** | **1180672** | **4.50391** | **4.50391** | **1594.8841** |
| &nbsp;&nbsp;block_13/bn | 1024 | 0.00391 | 0.00391 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_13/bn/beta | 512 | 0.00195 | 0.00195 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_13/bn/gamma | 512 | 0.00195 | 0.00195 | - |
| &nbsp;&nbsp;block_13/conv | 1179648 | 4.5 | 4.5 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_13/conv/kernel | 1179648 | 4.5 | 4.5 | - |
| **block_21** | **32896** | **0.12549** | **0.12549** | **44.30234** |
| &nbsp;&nbsp;block_21/bn | 128 | 0.00049 | 0.00049 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_21/bn/beta | 64 | 0.00024 | 0.00024 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_21/bn/gamma | 64 | 0.00024 | 0.00024 | - |
| &nbsp;&nbsp;block_21/conv | 32768 | 0.125 | 0.125 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_21/conv/kernel | 32768 | 0.125 | 0.125 | - |
| **block_14** | **4720640** | **18.00781** | **18.00781** | **1594.8841** |
| &nbsp;&nbsp;block_14/bn | 2048 | 0.00781 | 0.00781 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_14/bn/beta | 1024 | 0.00391 | 0.00391 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_14/bn/gamma | 1024 | 0.00391 | 0.00391 | - |
| &nbsp;&nbsp;block_14/conv | 4718592 | 18.0 | 18.0 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_14/conv/kernel | 4718592 | 18.0 | 18.0 | - |
| **block_15** | **525312** | **2.00391** | **2.00391** | **177.20934** |
| &nbsp;&nbsp;block_15/bn | 1024 | 0.00391 | 0.00391 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_15/bn/beta | 512 | 0.00195 | 0.00195 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_15/bn/gamma | 512 | 0.00195 | 0.00195 | - |
| &nbsp;&nbsp;block_15/conv | 524288 | 2.0 | 2.0 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_15/conv/kernel | 524288 | 2.0 | 2.0 | - |
| **block_16** | **4720640** | **18.00781** | **18.00781** | **1594.8841** |
| &nbsp;&nbsp;block_16/bn | 2048 | 0.00781 | 0.00781 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_16/bn/beta | 1024 | 0.00391 | 0.00391 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_16/bn/gamma | 1024 | 0.00391 | 0.00391 | - |
| &nbsp;&nbsp;block_16/conv | 4718592 | 18.0 | 18.0 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_16/conv/kernel | 4718592 | 18.0 | 18.0 | - |
| **block_17** | **525312** | **2.00391** | **2.00391** | **177.20934** |
| &nbsp;&nbsp;block_17/bn | 1024 | 0.00391 | 0.00391 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_17/bn/beta | 512 | 0.00195 | 0.00195 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_17/bn/gamma | 512 | 0.00195 | 0.00195 | - |
| &nbsp;&nbsp;block_17/conv | 524288 | 2.0 | 2.0 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_17/conv/kernel | 524288 | 2.0 | 2.0 | - |
| **block_18** | **4720640** | **18.00781** | **18.00781** | **1594.8841** |
| &nbsp;&nbsp;block_18/bn | 2048 | 0.00781 | 0.00781 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_18/bn/beta | 1024 | 0.00391 | 0.00391 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_18/bn/gamma | 1024 | 0.00391 | 0.00391 | - |
| &nbsp;&nbsp;block_18/conv | 4718592 | 18.0 | 18.0 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_18/conv/kernel | 4718592 | 18.0 | 18.0 | - |
| **block_19** | **9439232** | **36.00781** | **36.00781** | **3189.76819** |
| &nbsp;&nbsp;block_19/bn | 2048 | 0.00781 | 0.00781 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_19/bn/beta | 1024 | 0.00391 | 0.00391 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_19/bn/gamma | 1024 | 0.00391 | 0.00391 | - |
| &nbsp;&nbsp;block_19/conv | 9437184 | 36.0 | 36.0 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_19/conv/kernel | 9437184 | 36.0 | 36.0 | - |
| **block_20** | **9439232** | **36.00781** | **36.00781** | **3189.76819** |
| &nbsp;&nbsp;block_20/bn | 2048 | 0.00781 | 0.00781 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_20/bn/beta | 1024 | 0.00391 | 0.00391 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_20/bn/gamma | 1024 | 0.00391 | 0.00391 | - |
| &nbsp;&nbsp;block_20/conv | 9437184 | 36.0 | 36.0 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_20/conv/kernel | 9437184 | 36.0 | 36.0 | - |
| **block_22** | **11798528** | **45.00781** | **45.00781** | **3987.55635** |
| &nbsp;&nbsp;block_22/bn | 2048 | 0.00781 | 0.00781 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_22/bn/beta | 1024 | 0.00391 | 0.00391 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_22/bn/gamma | 1024 | 0.00391 | 0.00391 | - |
| &nbsp;&nbsp;block_22/conv | 11796480 | 45.0 | 45.0 | - |
| &nbsp;&nbsp;&nbsp;&nbsp;block_22/conv/kernel | 11796480 | 45.0 | 45.0 | - |
| **conv_23** | **128125** | **0.48876** | **0.48876** | **43.28513** |
| &nbsp;&nbsp;conv_23/bias | 125 | 0.00048 | 0.00048 | - |
| &nbsp;&nbsp;conv_23/kernel | 128000 | 0.48828 | 0.48828 | - |

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature / Optimization (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by iizukak** [comment]
@nlpng @lm-jira Can you review this?

**Comment by lm-jira** [comment]
@ruimashita 
I tried this command.
```
$ docker-compose -p lmnet run --rm cpu-tensorflow python3 executor/profile_model.py -c configs/core/object_detection/yolo_v2_quantize_pascalvoc_2007_2012.py
```
but it shows only the number of parameters and FLOPs but no Size (MB) and 32 bits Quant Size information. 
Should it show the same result as your table?

**Comment by ruimashita** [comment]
@lm-jira 
Thanks. Yes, It should show.
Plz post result

**Comment by lm-jira** [comment]
@ruimashita 
Here is the result.

```
==================Model Analysis Report======================
node name | # parameters
_TFProfRoot (--/50.66m params)
  block_1 (--/928 params)
    block_1/bn (--/64 params)
      block_1/bn/beta (32, 32/32 params)
      block_1/bn/gamma (32, 32/32 params)
    block_1/conv (--/864 params)
      block_1/conv/kernel (3x3x3x32, 864/864 params)
  block_10 (--/131.58k params)
    block_10/bn (--/512 params)
      block_10/bn/beta (256, 256/256 params)
      block_10/bn/gamma (256, 256/256 params)
    block_10/conv (--/131.07k params)
      block_10/conv/kernel (1x1x512x256, 131.07k/131.07k params)
  block_11 (--/1.18m params)
    block_11/bn (--/1.02k params)
      block_11/bn/beta (512, 512/512 params)
      block_11/bn/gamma (512, 512/512 params)
    block_11/conv (--/1.18m params)
      block_11/conv/kernel (3x3x256x512, 1.18m/1.18m params)
...


==================Model Analysis Report======================
node name | # float_ops
_TFProfRoot (--/29.36b flops)
  import/block_22/conv/Conv2D (3.99b/3.99b flops)
  import/block_20/conv/Conv2D (3.19b/3.19b flops)
  import/block_19/conv/Conv2D (3.19b/3.19b flops)
  import/block_3/conv/Conv2D (1.59b/1.59b flops)
  import/block_8/conv/Conv2D (1.59b/1.59b flops)
  import/block_9/conv/Conv2D (1.59b/1.59b flops)
  import/block_2/conv/Conv2D (1.59b/1.59b flops)
  import/block_18/conv/Conv2D (1.59b/1.59b flops)
  import/block_16/conv/Conv2D (1.59b/1.59b flops)
  import/block_14/conv/Conv2D (1.59b/1.59b flops
...
```

**Comment by ruimashita** [comment]
@lm-jira 
Oh, This is just prompt. The script output the markdown file

**Comment by lm-jira** [comment]
@ruimashita 
I got it. It works as expected.

**Pull request merged**
