### PR TITLE
Add toolchain for AArch64

### PR DESCRIPTION
**Pull request by primenumber**
## Motivation and Context

This PR enable to build aarch64 binary using CMake.

## Description

- Add toolchain file for AArch64

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature / Optimization (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by primenumber** [comment]
run test

**Comment by ruimashita** [comment]
@primenumber 
Thanks 👍 
What command can I verify this PR with?

**Comment by primenumber** [comment]
@ruimashita 
I checked
```shell
$ PYTHONPATH=python/dlk python python/dlk/scripts/generate_project.py -i examples/segmentation/lm_segnet_v1_quantize_camvid/minimal_graph_with_shape.pb -o tmp/ -p segmentaion -hq -ts
$ cd tmp/segmentation.prj
$ mkdir build
$ cd build
$ cmake -DTOOLCHAIN_NAME=linux_aarch64 ..
$ make -j8 lm
```

**Comment by ruimashita** [comment]
@primenumber 
Thanks, I will verify commands 😄

**Comment by ruimashita** [comment]
Works fine with qemu 
```
$ qemu-aarch64-static ./lm_aarch64 ../../../dlk/examples/segmentation/lm_segnet_v1_quantize_camvid/network_input_output/000_images_placeholder\:0.npy ../../../dlk/examples/segmentation/lm_segnet_v1_quantize_camvid/network_input_output/227_output\:0.npy


-------------------------------------------------------------
Comparison: Default network test  succeeded!!!
-------------------------------------------------------------
ApplyThresholds,15060,11695,19312,21311,19583,20410,33908,159165,83682,67493,  sum:451.619ms
BatchNorm,23928,  sum:23.928ms
Convolution,302335,  sum:302.335ms
DepthToSpace,1117,5458,5087,  sum:11.662ms
ExtractImagePatches,2550,2061,710,  sum:5.321ms
Memcpy,190,139,165,173,158,155,237,551,837,  sum:2.605ms
QTZ_linear_mid_tread_half,56886,  sum:56.886ms
QuantizedConv2D,2.28444e+07,2.31018e+07,4.23371e+07,4.24748e+07,4.54853e+07,4.66015e+07,4.76624e+07,9.35674e+07,9.4121e+07,9.38683e+07,  sum:552064ms
Tensor convert,175,791,553,736,745,722,738,1277,4373,6163,  sum:16.273ms
TotalInitTime,85515,  sum:85.515ms
TotalRunTime,5.52578e+08,  sum:552578ms
kn2row-1x1,302122,  sum:302.122ms
linear_to_float,105090,  sum:105.09ms
matrix_multiplication,302017,  sum:302.017ms
matrix_shift_add1,2866,3211,9298,9552,9929,8970,9987,16547,17567,18753,  sum:106.68ms
matrix_shift_add2,37377,31515,28991,29940,30210,28326,72752,160187,340989,382802,  sum:1143.09ms
pack_input,19609,  sum:19.609ms
quantized-kn2row,2.2844e+07,2.31009e+07,4.23366e+07,4.2474e+07,4.54846e+07,4.66007e+07,4.76616e+07,9.35661e+07,9.41165e+07,9.38621e+07,  sum:552047ms
quantized_matrix_multiplication,2.2773e+07,2.30432e+07,4.22667e+07,4.24006e+07,4.54116e+07,4.65274e+07,4.75165e+07,9.31405e+07,9.355e+07,9.32973e+07,  sum:549927ms
---------------------------------------------------
TotalInitTime 85440,  sum:85.44ms
TotalRunTime 5.52578e+08,  sum:552578ms
..ExtractImagePatches 2539,2057,707,  sum:5.303ms
..Convolution 302334,  sum:302.334ms
....kn2row-1x1 302118,  sum:302.118ms
......matrix_multiplication 302009,  sum:302.009ms
..BatchNorm 23925,  sum:23.925ms
..QTZ_linear_mid_tread_half 56882,  sum:56.882ms
....pack_input 19605,  sum:19.605ms
..QuantizedConv2D 2.28444e+07,2.31018e+07,4.23371e+07,4.24748e+07,4.54853e+07,4.66015e+07,4.76624e+07,9.35674e+07,9.4121e+07,9.38683e+07,  sum:552064ms
....Tensor convert 171,788,551,733,742,719,735,1275,4370,6160,  sum:16.244ms
....quantized-kn2row 2.2844e+07,2.31009e+07,4.23365e+07,4.2474e+07,4.54846e+07,4.66007e+07,4.76616e+07,9.35661e+07,9.41165e+07,9.38621e+07,  sum:552047ms
......quantized_matrix_multiplication 2.2773e+07,2.30432e+07,4.22667e+07,4.24006e+07,4.54116e+07,4.65274e+07,4.75165e+07,9.31405e+07,9.355e+07,9.32973e+07,  sum:549927ms
......matrix_shift_add1 2863,3208,9293,9547,9924,8966,9981,16540,17561,18747,  sum:106.63ms
......matrix_shift_add2 37370,31510,28985,29933,30203,28319,72745,160182,340983,382796,  sum:1143.03ms
......ApplyThresholds 15057,11692,19309,21307,19580,20407,33905,159161,83677,67489,  sum:451.584ms
..Memcpy 187,137,162,170,155,152,234,549,834,  sum:2.58ms
..DepthToSpace 1113,5455,5085,  sum:11.653ms
..linear_to_float 105085,  sum:105.085ms

```

**Pull request merged**
