### PR TITLE
Change the default value of save_npy_for_debug for convert command

### PR DESCRIPTION
**Pull request by hadusam**
Related #750 
`save_npy_for_debug` is for debug, so I would like to change the default value from `True` to `False`.

### CODE REVIEW

**Comment by iizukak** [comment]
@hadusam 
Thank you for adding options.
I think adding option is not problem.

But, We want npy files often to run lm_*.so files.
The default `True` value is good for me.

**Comment by hadusam** [comment]
@iizukak 
Oh, thank you!
I understand we often need npy files. 😱 
In this situation, what do you think about #750 ?
Is it better not to provide CPU docker image currently? Should we wait to fix the root cause of the error of saving npy files on CPU mode? 🤔

**Comment by tkng** [comment]
> In this situation, what do you think about #750 ?

I think a better answer is to make `save_npy_for_debug` option work on CPU version of Docker Image. (If possible.)

**Comment by hadusam** [comment]
After #789, we can save `npy` files without errors, so this change is not necessary now.

**Pull request closed without merging**
