### PR TITLE
Add docker build step at the beginning of all CI pipeline

### PR DESCRIPTION
**Pull request by tfujiwar**
## What this patch does to fix the issue.
In CI, Building the same docker image at the same time sometimes causes an error. So I added a common "docker build" step at the beginning of all CI pipelines. It avoids CI pipelines to build the same docker image many times.

## Link to any relevant issues or pull requests.
Issue #901 .

### CODE REVIEW

**Comment by iizukak** [comment]
@tfujiwar 
OK Thanks. We want stable CI strongly.

Please teach me Fujiwara-sense,
Why this diff can avoid simultaneous build of Docker image?
Before this diff, 

```
command: "make test-classification"
command: "make test-dlk-main"
command: "make test-unit-main"
```

build docker image as their dependency, In you PR, call `make build` explicitly, I'm not sure why this can avoid simultaneous build.

**Comment by tfujiwar** [comment]
@iizukak Sorry for lacking the information.

In `blueoil-pipeline.yml` for example, without this PR, 4 main steps run in parallel. It may cause an error.
```
┬-> make test-classification
├-> make test-object-detection
├-> make test-semantic-segmentation
└-> make test-keypoint-detection
```

With this PR, I added a `docker build` step and `wait` step at the beginning. So the following main 4 steps cannot start before `docker build` step finishes.
https://buildkite.com/docs/pipelines/wait-step
```
docker build ┬-> make test-classification
             ├-> make test-object-detection
             ├-> make test-semantic-segmentation
             └-> make test-keypoint-detection
```

Adding `docker build` step and `wait` step is enough for avoiding parallel builds in one pipeline but we need to think about avoiding parallel builds among all pipelines. So I specified `concurrency` and `concurrency_group` to the docker build step. With these settings, we can limit the parallel number of jobs that belong to the same `concurrency_group` on the organization level.
https://buildkite.com/docs/pipelines/controlling-concurrency
```
concurrency: 1
concurrency_group: "docker/gpu/${BUILDKITE_COMMIT}"
```

**Comment by iizukak** [comment]
Ownership Approval

**Pull request merged**
