### PR TITLE
Remove unused DLK readme files

### PR DESCRIPTION
**Pull request by Joeper214**
## What this patch does to fix the issue.
These Docs is not used and maintained anymore so It's better to get rid of them.
## Link to any relevant issues or pull requests.
n/a

### CODE REVIEW

**Comment by iizukak** [comment]
@Joeper214 
Thanks you for the refactor.
Theses files are mostly deprecated, but some of the information is useful, for example `dlk/README.md` contains description about `generate_project.py`.
Before remove, we should consider which description is necessary...

**Comment by Joeper214** [comment]
plocy.md

**Comment by iizukak** [comment]
@Joeper214 Agreed.

**Comment by kchygoe** [comment]
Can you fix the `index.rst` along with your change?

**Comment by Joeper214** [comment]
@iizukak @kchygoe I updated the PR again based on the previous comments. Please check PR again.

**Comment by iizukak** [comment]
@Joeper214 
In `README.md, There is some description about `generate_project.py` and that needed.
In `setup_board.md`, There is some description about DE10-Nano boards.
I think these source should be move to other documentation.
You have plan to create new documentation after this PR merged?

**Comment by Joeper214** [comment]
@iizukak I added `docs/dlk/overview.md` on index.rst and trimmed the necessary information. Please check again. 🙇

**Pull request merged**
