### PR TITLE
Remove unused  dlk/.github/CODEOWNERS file

### PR DESCRIPTION
**Pull request by ruimashita**
## Motivation and Context

In order to maintain our codebase, remove unused dlk/.github/CODEOWNERS file.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature / Optimization (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ruimashita** [comment]
@iizukak @nlpng Review please 👍

**Comment by iizukak** [comment]
@ruimashita What is the purpose of this PR?

**Comment by ruimashita** [comment]
@iizukak 
Purpose is to maintain our codebase,

**Comment by ruimashita** [comment]
run dlk test

**Pull request merged**
