### PR TITLE
Reduce load time in apply_threshold

### PR DESCRIPTION
**Pull request by lm-konda**
## Motivation and Context
apply_threshold costs a lot specially on AArch64 and ARM.
So in order to reduce execution time, modify code.

## Description
Improve performance by loading after branching by if statement.
Although the code becomes dirty, the number of loads can be reduced.

Performance improvement can also be expected with aarch64.

gist (config file)
https://gist.github.com/lm-konda/650998a61dc5077514fd0531b4fde51c

## How has this been tested?
run on ARM / FPGA / X86

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature / Optimization (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by lm-konda** [comment]
performance change (ARM)
before
```
TotalRunTime,730681,  sum:730.681ms
```
after
```
TotalRunTime,721388,  sum:721.388ms
```

**Comment by tkng** [comment]
For me, it looks that the compiler will be able to optimize this kind of things.

Also, 9ms of 730ms looks within the fructuation. Could you run more experiments to confirm the effetiveness?

**Comment by lm-konda** [comment]
OK. I will try more times.

**Comment by lm-konda** [comment]
As a result, the number of instructions (insn) decreases
when array access is inlined in the if statement as well.

Reason:
I took a profile that I ran 10 times using perf.
There was hardly shake of insn.

original
38,962,520,232
tuned
38,903,410,658

gist (log)
original
https://gist.github.com/lm-konda/f63ede25b476b04c8dc0d309cfcc8793

tuned
https://gist.github.com/lm-konda/cc8c8af836ea50a420dc1f17f44ca363

**Comment by iizukak** [comment]
This PR has no progress recently, So I close this PR temporary.

**Pull request closed without merging**
