### PR TITLE
Move executor scripts which exist only in “lmnet/executor”

### PR DESCRIPTION
**Pull request by tfujiwar**
Related to #746 .

This PR moves executor scripts which exist only in `lmnet/executor` to `blueoil/cmd`. This change has no conflicts with the existing scripts in `blueoil/cmd`. So the target scripts are simply moved. Paths in code, comments and docs which point the target scripts are updated.

Target scripts:
- build_tfds.py
- convert_weight_from_darknet.py (will be deleted: #781)
- evaluate.py
- export.py
- measure_latency.py
- output_event.py
- profile_model.py
- profile_template.md
- tune_ray.py

### CODE REVIEW

**Comment by iizukak** [comment]
@tfujiwar Wow, this PR is what I want!!

**Comment by tfujiwar** [comment]
@iizukak 
I agree with putting images (and `profile_template.md` also) in the other folder but I'm not sure it's good to put them inside `tests` folder because they are not for testing.

How about `blueoil/cmd/fixtures` ?

**Comment by iizukak** [comment]
`blueoil/cmd/fixtures` is nice.

**Pull request merged**
