### PR TITLE
change python to python3 in usage docs

### PR DESCRIPTION
**Pull request by joelN123**
This PR is for the following issue https://github.com/blue-oil/blueoil/issues/1188. The point is simply to change the documentation of Blueoil command from `python` (which causes error in the docker container), to `python3`.

There is also documentation that mentions `python` in [converter/overview.md](https://github.com/blue-oil/blueoil/blob/master/docs/converter/overview.md), [converter/shared_library.md](https://github.com/blue-oil/blueoil/blob/master/docs/converter/shared_library.md), and several files in docs/tutorial. But in each of those cases, it looks like it is being explained from the perspective of outside a container, where someone would likely be using a python environment etc. So I didn't change the documentation in those cases.

### testing it out

I'm not sure it was really necessary, but I ran (using python3, rather than simply python) each of : init, train, convert, predict, export, evaluate, measure_latency, profile_model (for cifar classification), in the style of
```
docker run --runtime=nvidia -e CUDA_VISIBLE_DEVICES="0" -e PYTHONPATH=.:lmnet:dlk/python/dlk --rm -it -v `pwd`:/home/blueoil -w /home/blueoil -v <path to dataset dir>:/home/blueoil/dataset:ro --user=$(id -u):$(id -g) <docker image> python3 blueoil/cmd/main.py <specific command>
```
(or in some cases, like blueoil/cmd/\<specific command\>.py). They all seemed to run fine.

### CODE REVIEW

**Comment by joelN123** [comment]
run test

**Review by iizukak — APPROVED** [review]
OA
Thanks.

**Pull request merged**
