### PR TITLE
Move lmnet/lmnet/datasets to blueoil/datasets

### PR DESCRIPTION
**Pull request by iizukak**
This PR is a part of #796
I moved `lmnet/lmnet/datasets` to `blueoil/datasets`

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by odoku** [comment]
@iizukak 
I don't think Datasets are strictly related to Neural Network.
So it seems unnatural to have datasets under the nn directory. What do you think?

I think it is easy to discuss if there is a definition of what the nn module handles.

**Comment by odoku** [comment]
You said you're not sure it's right to have the module directory at the same level as the cmd directory, but it doesn't seem to matter as far as you look at the famous libraries.

* [Scrapy](https://github.com/scrapy/scrapy/blob/master/setup.py#L43)
* [flake8](https://github.com/PyCQA/flake8/blob/master/setup.cfg#L62)
* [mypy](https://github.com/python/mypy/blob/master/setup.py#L183)

**Comment by iizukak** [comment]
@odoku 
Year, I agreed with you.

**Comment by iizukak** [comment]
@odoku `blueoil/nn/datasets` to `blueoil/datasets` moved. please review.

**Pull request merged**
