### PR TITLE
Tca xilinx support

### PR DESCRIPTION
**Pull request by lm-lily**
Add Xilinx ultra96 support.

## Motivation and Context

Add support to Xilinx.

## Description

Added all necessary files to support ultra96 board of Xilinx.

## How has this been tested?

Tested run on ultra96 board.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature / Optimization (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by iizukak** [comment]
@lm-lily Thanks to added support Ultra96.
I want to merge `tca_support` branch then merge this PR to master.
Can you wait for `tca_support` ?

**Comment by lm-lily** [comment]
Ok, thank you @iizukak.

**Comment by n-nez** [comment]
@iizukak, @lm-lily sorry for late.

**Comment by n-nez** [comment]
@iizukak yep I believe it is good to just add the project, and then target "dlk" changes in other PRs.

**Pull request closed without merging**
