### PR TITLE
Add try catch to ensure queue import compatibility

### LINKED ISSUE #259: usb_camera_demo.py doesn't work with python3
Tried this on `v0.6.0`

When I tried to run usb_camera_demo in Jetson TX2 with python3 it raises an import error.

I think `from Queue import Queue` doesn't work with python3.

https://github.com/blue-oil/blueoil/blob/3215aa45164da782fe15eb78ebc6bd7ead927be7/output_template/python/lmnet/utils/demo.py#L22

May we try to use `from multiprocessing import Queue` that is compatible with both?

### PR DESCRIPTION
**Pull request by Joeper214**
## Description

- add try catch and cross py2-py3 compatible version in demo.py
- fix #259 

## How has this been tested?

I'll test this on FPGA and Jetson TX2 once I have one available.

With these scripts.
usb_camera_demo.py
run.py
motion_jpeg_server_from_camera.py

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature / Optimization (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by hadusam** [comment]
run dlk test

**Comment by ruimashita** [comment]
@Joeper214 How did you test this ? It looks doesn't work.

**Comment by Joeper214** [comment]
@ruimashita Sorry Haven't tested it yet. 
I'll test this on FPGA and Jetson TX2 once I have one available. 

With these scripts.
`usb_camera_demo.py`
`run.py`
`motion_jpeg_server_from_camera.py`

**Comment by Joeper214** [comment]
@ruimashita Thanks for the review. I updated and tested on FPGA and Jetson Tx2. Seem to work on my side. Please check again if you have time.

**Pull request merged**
