### PR TITLE
Remove error from make html doc and update converter doc using Sphinx-apidoc

### PR DESCRIPTION
**Pull request by oatawa1**
## What this patch does to fix the issue.
Remove error when generate doc using `make html` which mainly from reference error.
- For converter update using autogenerate from `Sphinx-apidoc`.
- For `optimization.rst`, I fix it but I think this file is obsolete. **Shall we remove it?**: removed

## Link to any relevant issues or pull requests.
#953 (Error part) 
The warning part will be solved in another PR to reduce the amount of commit code.

### CODE REVIEW

**Comment by iizukak** [comment]
@oatawa1 Thanks. We can remove `optimization.rst,`

**Comment by oatawa1** [comment]
@iizukak Thanks. I removed it in the latest commit

**Comment by oatawa1** [comment]
The deployment version is different from the local test version. I will fix it

**Comment by oatawa1** [comment]
@iizukak Thanks.

Can I merge this PR?

The current problem is the current deployment version show only the class name it should show both class name along with module and arg name.
https://deploy-preview-989--blueoil.netlify.com/converter/converter.core.html

In my opinion, I want to merge this one to fix the error problem.
Then, this Python API will be removed in next PR, because I will migrate the Python API doc to autogenerate.

**Comment by oatawa1** [comment]
The problem of deployment is fixed in #995 . So I merged this PR.

**Pull request merged**
