### PR TITLE
Move blueoil/nn/quantizations to blueoil/quantizations

### PR DESCRIPTION
**Pull request by oatawa1**
## What this patch does to fix the issue.
I moved `blueoil/nn/quantization` to `blueoil/quantization` to keep the directory structure flat.

## Link to any relevant issues or pull requests.
#858

### CODE REVIEW

**Comment by iizukak** [comment]
@oatawa1 Commit log looks something wrong...

**Comment by oatawa1** [comment]
@iizukak I think I did something wrong with my repository.

I want to commit only this `Move blueoil/nn/quantizations to blueoil/quantizations`.

**Comment by iizukak** [comment]
@oatawa1 
Umm, can you fix?

**Comment by oatawa1** [comment]
@iizukak I 'm not sure about how to fix, but I will try to fix it.

**Comment by oatawa1** [comment]
@iizukak  I did open new PR in #862 to solve this problem.

Please correct me if I did it the wrong way.

**Comment by iizukak** [comment]
@oatawa1 Thanks

**Pull request closed without merging**
