### PR TITLE
Fix makefile tpl and add alias

### PR DESCRIPTION
**Pull request by yd8534976**
- Fix Makefile.tpl
- Add alias for GatherV2
- Fix typo

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature / Optimization (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by iizukak** [comment]
@yd8534976 Can you update your branch with current master?
like `git rebase -i upstream/master`.

**Comment by yd8534976** [comment]
@iizukak Okay, I will try it.

**Comment by yd8534976** [comment]
run test

**Comment by yd8534976** [comment]
@iizukak I have updated this branch, but test environments look strange. 🤔

**Comment by iizukak** [comment]
Thanks. Yes, Jenkins looks something wrong...

**Comment by yd8534976** [comment]
@iizukak Ok, I will close this PR and re make.

**Comment by yd8534976** [comment]
run test

**Pull request closed without merging**
