### PR TITLE
replace sprintf for ostringstream(#1192)

### PR DESCRIPTION
**Pull request by lm-kajihara**
#1192

### CODE REVIEW

**Review by iizukak — APPROVED** [review]
OA

**Review by primenumber — APPROVED** [review]
RA

**Comment by iizukak** [comment]
@tfujiwar buildkite/dlk-test failed. Could you check?

**Comment by tfujiwar** [comment]
The FPGA board was hanged. Now retrying the test.

**Comment by iizukak** [comment]
@tfujiwar Thanks.

**Comment by primenumber** [comment]
CLA needed?

**Comment by primenumber** [comment]
@lm-kajihara

**Pull request merged**
