### PR TITLE
Fix comment typo in __inin__.py in blueoil/blueoil/quantizations

### PR DESCRIPTION
**Pull request by oatawa1**
## What this patch does to fix the issue.
Fix comment typo

### CODE REVIEW

**Comment by oatawa1** [comment]
@iizukak  Thank you.

**Comment by oatawa1** [comment]
@tsawada Thank you.

**Comment by tsawada** [comment]
Didn't notice a typo in the commit message 😭

**Comment by oatawa1** [comment]
@tsawada 😭 I'm sorry. What should I do?

**Comment by tsawada** [comment]
Nothing. Just forget about it 😄

**Pull request merged**
