### PR TITLE
Moved dlk/docs to top directory. (#603)

### PR DESCRIPTION
**Pull request by ed728**
As per #603 moved the `docs` directory to the top level. Checked that all files are correctly moved.
## Description

-Moved dlk/docs/python and dlk/docs/README.md to docs/.
-Removed dlk/docs/Makefile and integrated its functionality into docs/Makefile.
-Removed docs/python/modules.rst and docs/python/our_api.rst.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature / Optimization (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ed728** [comment]
@iizukak The extra `docs/docs` thing was an accident, my bad... I have fixed that and added some changes. I have also documented what has changed in a more detailed manner.

**Comment by iizukak** [comment]
Thanks. docs directory wii include both lmnet and elk docs. The directory structure should be considered that.

**Comment by ed728** [comment]
@iizukak So would having `docs/lmnet` and `docs/dlk` be a good idea?

**Comment by iizukak** [comment]
@ed728 
Yes, but Sorry, After I commted, #786 was merged.

**Comment by kchygoe** [comment]
@ed728 sorry, I haven't noticed about this PR and created same PR! 
Now let's  work on `docs/` to be improved :)

**Comment by kchygoe** [comment]
let me close

**Pull request closed without merging**
