### PR TITLE
Update PYTHONPATH for main.py in document

### LINKED ISSUE #1046: Wrong PYTHONPATH in some documents
Some documents under `blueoil/docs/usage` directory refer to wrong PYTHONPATH like `PYTHONPATH=.:lmnet:dlk/python/dlk`.
Maybe they look too old and should be fixed.

### PR DESCRIPTION
**Pull request by oatawa1**
## What this patch does to fix the issue.
Some documents under `blueoil/docs/usage` directory refer to obsolete `PYTHONPATH`.
This PR update the `PYTHONPATH`.

## Link to any relevant issues or pull requests.
Closes #1046

### CODE REVIEW

**Comment by iizukak** [comment]
@oatawa1 In my understand, We do not need `PYTHONPATH` anymore.

**Comment by oatawa1** [comment]
I think we don't need it when we install blueoil via `pip -e .[cpu]` or `pip -e .[gpu]`, 

But if we manually install the package via pip, we may need it. Precisely only `PYTHONPATH=.`
If not it will throw this error.
```
Traceback (most recent call last):
  File "blueoil/cmd/main.py", line 21, in <module>
    from blueoil.cmd.convert import convert as run_convert
ModuleNotFoundError: No module named 'blueoil'
```

My solution will be update the document about installation because we currently don't have it and remove PYTHONPATH from this PR.

I

**Comment by oatawa1** [comment]
@iizukak Thank you.

**Pull request merged**
