### PR TITLE
[WIP] Remove test fixutures from repo

### LINKED ISSUE #980: Want fixures out of repo
`tests/fixtures` dir is so big and image files should be kept out from the repo.

### PR DESCRIPTION
**Pull request by kchygoe**
Migrate the files into blueoil bucket

## What this patch does to fix the issue.
Reducing Repository size

## Link to any relevant issues or pull requests.
Fix #980

### CODE REVIEW

**Comment by iizukak** [comment]
@kchygoe 
When we update fixtures, We need re-upload these files.
How to update resources?

**Comment by kchygoe** [comment]
@iizukak I will implement the make commands for those. thx for the comment!

**Comment by iizukak** [comment]
@kchygoe How about progress of this PR?

**Comment by kchygoe** [comment]
@iizukak sorry for being late. I need around a week to go. I'll let you know soon

**Comment by iizukak** [comment]
@kchygoe No problem sir.

**Pull request closed without merging**
