### PR TITLE
[WIP] lmnet: Add cityscapes loader

### PR DESCRIPTION
**Pull request by tsawada**
Ref #208

### CODE REVIEW

**Comment by tsawada** [comment]
CC @nlpng @iizukak

**Comment by tsawada** [comment]
This works, but needs more work:
* Ignore certain classes for evaluation: See https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/helpers/labels.py for which classes to ignore
* test needs `/storage/dataset/cityscapes`

**Comment by Joeper214** [comment]
@iizukak I is okay to pass then merge this PR first then create another issue for more work to be done?

**Comment by Joeper214** [comment]
run test

**Pull request closed without merging**
