### PR TITLE
Move blueoil/nn/quantizations to blueoil/quantizations

### PR DESCRIPTION
**Pull request by oatawa1**
## What this patch does to fix the issue.
I moved blueoil `/nn/quantization` to `blueoil/quantization` to keep the directory structure flat.
Resolved problem of commit log in #860 .

## Link to any relevant issues or pull requests.
#858

### CODE REVIEW

**Comment by tfujiwar** [comment]
@oatawa1 Could you try pushing `update branch`? I don't know why but I couldn't though the button is displayed.

**Comment by Joeper214** [comment]
Looks like Github is Having a bug here.

**Comment by oatawa1** [comment]
Updated Branch now.

**Pull request merged**
