### PR TITLE
Fix Makefile.tpl

### PR DESCRIPTION
**Pull request by yd8534976**
- Fix broken `make clean`, `make test`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature / Optimization (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by iizukak** [comment]
@yd8534976 
Thank you for fix suggestion!!

I don't know current Makefile is broken....
In this PR, Please remove the code using `TARGETS`.
 then add correct `clean` `test` and `all` 🤓

**Comment by yd8534976** [comment]
@iizukak 
- Remove code using `TARGETS`.
- Since we can not make another targets before removing last object files. `make all` will not work. I directly delete `make all`.
- Since `lm_xx.elf` need `xx.npy` file to test, `make test` will not work too. I delete it too.
- `make clean` also removes `*.elf` and `*.so` now.
- Since current `lm_xx.elf` are used to test, I want to add `-DFUNC_TIME_MEASUREMENT` to all `lm_xx` targets. Is it okay to add this change into this PR or make a new PR?

**Comment by iizukak** [comment]
@yd8534976 Thanks~

> Since current lm_xx.elf files are used to test, I want to add -DFUNC_TIME_MEASUREMENT to all lm_xx targets. Is it okay to add this change into this PR or make a new PR?

This idea is reasonable. Please make new PR

**Comment by yd8534976** [comment]
@iizukak 

> Since current lm_xx.elf files are used to test, I want to add -DFUNC_TIME_MEASUREMENT to all lm_xx targets. Is it okay to add this change into this PR or make a new PR?

I didn't know https://github.com/blue-oil/blueoil/pull/330 had been doing this change. 🤣

**Pull request merged**
