### PR TITLE
Remove blueoil.sh, blueoil_test.sh

### PR DESCRIPTION
**Pull request by suttang**
## Motivation and Context

To complete rebuilding project, I removed blueoil.sh.

## Description

- Remove `blueoil.sh`
- Remove `blueoil_test.sh`
- Edit `Dockerfile` for test
- Edit `Makefile` for test

## How has this been tested?

```
$ CUDA_VISIBLE_DEVICES=4 make test
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature / Optimization (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by iizukak** [comment]
I'll check script manually.
Please wait a while.

**Comment by suttang** [comment]
Error log

```
[2019-11-05T14:30:05Z] E     tensorflow.python.framework.errors_impl.OutOfRangeError: Node 'conv1/BatchNorm/FusedBatchNorm' (type: '_FusedConv2D', num of outputs: 1) does not have output 1
```

**Comment by suttang** [comment]
This error is similar to this issue #424

**Comment by hadusam** [comment]
@suttang 
This is similar but not same as that issue.
```
[2019-11-05T14:36:03Z] 2019-11-05 14:30:23.751862: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
```
I have not seen this error and there is no other message about `cuda` ... 🤔 
On the other hand, the current latest docker image passed tests, so please update this branch by resolving conflicts, it may help to pass tests.

**Comment by suttang** [comment]
@hadusam Thank you!! CI test passed!!

**Pull request merged**
