### PR TITLE
Add CODEOWNERS file

### PR DESCRIPTION
**Pull request by hadusam**
Add CODEOWNERS file for Bot.

### CODE REVIEW

**Comment by hadusam** [comment]
@iizukak 
Oh, sorry for less information.
This is for reviewer assign system.

**Comment by iizukak** [comment]
@hadusam 
How about readablility reviewer? Add later?

**Comment by hadusam** [comment]
@iizukak 
Readability Reviewers are defined as Github Teams.
You can see the teams on https://github.com/orgs/blue-oil/teams

The bot will be installed on 12/6 Fri after the explanation with documents of how to approve reviews. 👍 
It is necessary to merge this PR before bot installation. Sorry for fewer communications 🙇

**Comment by iizukak** [comment]
@hadusam 
Thank you for the information.
I understood...
Little question, why ownership reviewer is in CODEOWNERS.yaml not Github Teams?

And how about add Shell and Docker Readability reviewer ? :)

**Comment by hadusam** [comment]
@iizukak 
> why ownership reviewer is in CODEOWNERS.yaml not Github Teams?

Good question!
At first, we need to specify owners on each directory, and we have many repositories on internal company org, so owner's lists are variable and we should support to be specified username on code owners file. Thus, currently, only supported username, but of course, I think teams for code owners will be supported in the future.

> And how about add Shell and Docker Readability reviewer ? :)

That sounds great! Let's discuss it later. :)

**Pull request merged**
