### PR TITLE
[WIP] Merge requirements.txt for cpu and gpu along with tensorflow==1.15

### PR DESCRIPTION
**Pull request by kchygoe**
## Motivation and Context

tensorflow now supports GPU natively in the package tensorflow from
the version 1.15.
so we can merge those many requirements.txt

## Description

- merge cpu.requirements.txt and gpu.requirements.txt into
requirements.txt
- use dev.requirements.txt in docker installation(this has to be
reviewed in other issue)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature / Optimization (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by iizukak** [comment]
@kchygoe Nice PR.
How TensorFlow decide use GPU or not?
check `CUDA_VISIBLE_DEVICE` or check CUDA driver?

**Comment by kchygoe** [comment]
@iizukak sorry, I was just trying to check with buildkite test, but let me check the details. As the double-check, could you check the behavior?

**Comment by kchygoe** [comment]
I run the docker image on the server with gpu but looks not visible from tensorflow. let me look deeper. sorry for the inconvenience.
```
>>> tf.config.experimental.list_physical_devices()
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:XLA_CPU:0', dev
ice_type='XLA_CPU')]
```

**Comment by iizukak** [comment]
@kchygoe Wow, thanks.

**Comment by kchygoe** [comment]
Sorry, my misunderstanding!!
1.15 has still difference between tensorflow package and tensorflow-gpu package.
From >1.15, they will be merged.

**Pull request closed without merging**
