### PR TITLE
Add favicon for documentation site.

### PR DESCRIPTION
**Pull request by toohsk**
## Motivation and Context

Issue was opened in below.
ref: https://github.com/blue-oil/blueoil/issues/57

As mentioned in issue, I add favicon for document site.

## Description

- Download favicon and add to `_static` directory
- Add a favicon file path to `config.py` 

## How has this been tested?

Not tested.
I read README but I couldn't find it.
Is there a test for docs?

## Screenshots (if appropriate):

I took a screanshot to confirm favicon is reflected.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature / Optimization (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ruimashita** [comment]
Jenkins, ok to test.

**Comment by ruimashita** [comment]
@toohsk 
> Is there a test for docs?

Currently We don't have test for docs, don't need to care it, Thanks 👍

**Comment by ruimashita** [comment]
I verified that I can see the favicon in some browsers on OSX.

Safari:
screen shot 2019-01-25 at 16 21 58

Chrome:
screen shot 2019-01-25 at 16 21 46

Firefox:
screen shot 2019-01-25 at 16 21 32

**Comment by ruimashita** [comment]
After CI test are passed, I will merge this PR into master.

**Comment by toohsk** [comment]
Thanks, @ruimashita !

**Comment by ruimashita** [comment]
@toohsk 
You are the first contributor excluding LeapMind Inc member, I'm so grateful to you 🎉🎉🎉

**Pull request merged**
