### PR TITLE
Rename depth to channels

### PR DESCRIPTION
**Pull request by primenumber**
## What this patch does to fix the issue.
there are several naming for 'number of channels in a layer: `depth` `channel` `channels`
This PR unify to `channels`.
kernel_depth (for convolution) -> input_channels
depths -> channels_list
channel -> channels
depth -> channels

### CODE REVIEW

**Comment by a-hanamoto** [comment]
Please assign a readability reviewer after getting OA.

**Comment by tkng** [comment]
RA

**Pull request merged**
