### PR TITLE
Fix check for activation quantizer counts of input in optimization pass

### PR DESCRIPTION
**Pull request by nlpng**
## Motivation and Context

This PR is trying to hot fix the issue of #173

## Description

Main change is in the `core/optimizer.py`.
This hot fix resolves following graph that with multiple concat ops:
screen shot 2019-03-01 at 9 54 00

## How has this been tested?

Manually tested with @n-nez and @antonionevado collaboratively

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature / Optimization (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by n-nez** [comment]
> Thanks. why we had the condition ? What we assumed to avoid by the condition ?

@antonionevado

**Comment by antonionevado** [comment]
@ruimashita @n-nez That condition is wrong. It was there to check that every input is quantized. But this situation proved that this way of checking is not good.

**Comment by antonionevado** [comment]
Oh ok. Actually we need to replace the old condition by something else.
@nlpng could you please add a condition that check if `qtzs` are all compatible?
In case they **are compatible** then this should happen:
```
quant_details[m.name] = qtzs
```
but if they are **not compatible** then it should happen:
```
quant_details[m.name] = []
```

**Comment by n-nez** [comment]
@antonionevado, @nlpng 
Would prefer to have a warning when we reject to quantize something because of `qtzs` is not compatible, as it sounds somewhat suspicious... :thinking:

**Comment by iizukak** [comment]
@ruimashita Please check this PR

**Comment by ruimashita** [comment]
I will review tomorrow ~

**Pull request merged**
