### PR TITLE
Fix condition

### LINKED ISSUE #152: Generic quantized multiplication is probably wrong
in src file：
　src/matrix/generic/quantized_multiplication.cpp

There are lines like follows.
```
            if (A.rows() - i > 0) {★
              T_UINT a = *A.data(i+0, j+j2);
              if (end - k > 0) CONV(0, 0)
              if (end - k > 1) CONV(0, 1)
              if (end - k > 2) CONV(0, 2)
              if (end - k > 3) CONV(0, 3)
            }
            if (A.rows() - i > 0) {★
              T_UINT a = *A.data(i+1, j+j2);
              if (end - k > 0) CONV(1, 0)
              if (end - k > 1) CONV(1, 1)
              if (end - k > 2) CONV(1, 2)
              if (end - k > 3) CONV(1, 3)
            }
            if (A.rows() - i > 0) {★
              T_UINT a = *A.data(i+2, j+j2);
              if (end - k > 0) CONV(2, 0)
              if (end - k > 1) CONV(2, 1)
              if (end - k > 2) CONV(2, 2)
              if (end - k > 3) CONV(2, 3)
            }
            if (A.rows() - i > 0) {★
              T_UINT a = *A.data(i+3, j+j2);
              if (end - k > 0) CONV(3, 0)
              if (end - k > 1) CONV(3, 1)
              if (end - k > 2) CONV(3, 2)
              if (end - k > 3) CONV(3, 3)
            }
```
It is not certain to me, but it seems to be an error in the branching condition.

(should be > 0, > 1, > 2, > 3?)

### PR DESCRIPTION
**Pull request by primenumber**
Fix #152 

## Motivation and Context

Quantized matrix multiplication may cause memory access error in current implementation when kernel size is not multiple of 4.

## Description

Fixed wrong condition

This fix is done by [#153](https://github.com/blue-oil/blueoil/pull/153), but the PR is conflict with master.
And the author is no longer working on the PR anymore.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature / Optimization (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by iizukak** [comment]
run dlk test

**Comment by iizukak** [comment]
run test

**Comment by tvlenin** [comment]
Guys this PR is not the same that #153? #153 was closed.

**Comment by primenumber** [comment]
@tvlenin Oh, that's right.
@iizukak What should we do? Reopen #153 ? Continue this PR?

**Comment by iizukak** [comment]
@tvlenin @primenumber 
It's ok to continue this PR.
#153 is developped by @lm-konda ,but not actively develop Blueoil.

**Comment by iizukak** [comment]
#153 needs some more work (conflict with master) but the author is no longer working on the PR anymore.

@primenumber Can you add link to #153 in PR description?

**Comment by iizukak** [comment]
@n-nez @antonionevado Please review.

**Comment by primenumber** [comment]
@iizukak Updated.

**Comment by iizukak** [comment]
@primenumber thanks.

**Pull request merged**
