### PR TITLE
lmnet: Add cityscapes loader

### PR DESCRIPTION
**Pull request by Joeper214**
## Motivation and Context

Taking over this PR: https://github.com/blue-oil/blueoil/pull/213

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature / Optimization (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Joeper214** [comment]
@iizukak @nlpng Please review if you have time. 🙇

**Comment by iizukak** [comment]
@Joeper214 Thanks.
@nlpng Can you execute experiment with Cityscapes?

**Comment by nlpng** [comment]
@Joeper214 
for a quick test, I got the following error of running `segnet_quantize_cityscapes.py`
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/huang/anaconda3/envs/blueoil/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/huang/blueoil/lmnet/lmnet/datasets/dataset_iterator.py", line 161, in run
    self.loop_body()
  File "/home/huang/blueoil/lmnet/lmnet/datasets/dataset_iterator.py", line 137, in loop_body
    task_list = self.gen_task(self.dataset.batch_size * 8)
  File "/home/huang/blueoil/lmnet/lmnet/datasets/dataset_iterator.py", line 121, in gen_task
    data_id = self.data_ids.pop()
IndexError: pop from empty list
```
I will look into it, maybe it is the problem of my environment.

**Comment by Joeper214** [comment]
@ruimashita Thanks for several comments. I updated the PR.



> Is it ok to add jpg and json files in point of view of license?

Regarding that, I used dummy images and data instead. Just to grasp the unit test 🤞 .

**Comment by Joeper214** [comment]
run test

**Comment by ruimashita** [comment]
Thanks 👍 
Current test image looks all black. Could you change to some meaningful image with label?

And I hope add test in 
https://github.com/blue-oil/blueoil/blob/master/lmnet/tests/check_dataset_storage.py
to count dataset number of images for each subset, classes.

**Comment by Joeper214** [comment]
@ruimashita I change the test images as requested. and added more test.

Please check again if you have time.

**Comment by Joeper214** [comment]
run test

**Comment by Joeper214** [comment]
run test

**Comment by Joeper214** [comment]
run dlk test

**Comment by iizukak** [comment]
@nlpng 
How about this issue. fixed?
https://github.com/blue-oil/blueoil/pull/300#issuecomment-498899307

**Comment by nlpng** [comment]
@iizukak 
Yes, it is fixed.

**Comment by iizukak** [comment]
@nlpng Thanks. Then this PR can be approved?

**Comment by Joeper214** [comment]
run lmnet test

**Comment by iizukak** [comment]
@ruimashita Please review again

**Comment by ruimashita** [comment]
@Joeper214 
The images come from https://unsplash.com which are free license, But where annotation data come from ?

**Comment by Joeper214** [comment]
> @Joeper214
> The images come from https://unsplash.com which are free license, But where annotation data come from ?

I annotated them by hand using VoTT then followed the format of cityscapes dataset. Based on the images.

**Comment by ruimashita** [comment]
@Joeper214 Wow!! Thanks 👍

**Comment by Joeper214** [comment]
run lmnet test

**Comment by Joeper214** [comment]
run blueoil test

**Pull request merged**
