### PR TITLE
Removed unused generate_consts.

### PR DESCRIPTION
**Pull request by ed728**
## Motivation and Context

https://github.com/blue-oil/blueoil/issues/314

## Description

I am pretty sure `generate_consts()` is an old thing we used to handle consts, and have switched to a different method with a different folder with several files of consts.

`grep "generate_consts" -r .` produces only `./dlk/python/dlk/code_generater.py:    def generate_consts(self) -> None:`, which makes we think it is not used. There may still be the possibility that it is called via some Python magic somewhere, but Jenkins tests should be sufficient to cover that.

## How has this been tested?

Jenkins.
It's an unused function, so don't see much testing that can be done.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue) (Maybe?)
- [ ] New feature / Optimization (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by iizukak** [comment]
run test

**Comment by yd8534976** [comment]
Thanks so much for fixing! But I think in this step, we may skip the `generate_const` step. Could you please test if dlk can compile a graph with `Const` node?
```
def generate_code_step(model: Model, config: Config) -> None:
    """Generate code for the model.

    Parameters
    ----------
    model : Model
        Model the code generation is based on

    config : Config
        Collection of configurations

    """
    graph: Graph = model.graph
    params = Params(graph, config)

    builder = CodeGenerater(graph,
                            params,
                            config)

    builder.reuse_output_buffers()
    builder.generate_files_from_template()
    builder.generate_inputs()

    if config.activate_hard_quantization:
        builder.generate_scaling_factors()

    if config.threshold_skipping:
        builder.generate_thresholds()

    if config.use_tvm:
        builder.generate_tvm_libraries()
```

**Comment by yd8534976** [comment]
@ed728 , maybe it is just elder version of `generate_inputs()`...

**Comment by ed728** [comment]
The old consts templates don't exist anymore, and now we have a consts folder, which is what functions like `generate_inputs` use.

**Comment by iizukak** [comment]
@nlpng Can you reveiw?

**Comment by iizukak** [comment]
@nlpng Please review

**Pull request merged**
