### PR TITLE
Remove scripts using darknet pretrained models

### PR DESCRIPTION
**Pull request by iizukak**
Solve #781 
Please review after #782 merged

### CODE REVIEW

**Comment by iizukak** [comment]
@tkng please review.

**Comment by tkng** [comment]
I'm not sure that we should remove these config files. Could you tell me your opinion?

**Comment by iizukak** [comment]
@tkng 
I haven't seen anyone using this feature after Blueoil v0.1 released.
I want to remove useless code for reduce maintenance cost.

**Comment by iizukak** [comment]
But in this case, `should` is too strong word, maybe...

**Comment by tkng** [comment]
OK, let's remove. (Personally, I used these files sometimes... but it's OK, I can copy these files to other directory before `git pull`.)

**Comment by tkng** [comment]
Ownership Approval
Readability Approval

**Comment by iizukak** [comment]
> Personally, I used these files sometimes... 

Wow, really, I don't know that...

**Pull request merged**
